# Generated by Django 4.1.3 on 2023-03-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0002_alter_menu_options_remove_menu_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
    ]
